<?php
        $ages = array(''=>'Please Select',
            'Under 18'=>'Under 18',
            '18-25'=>'18-25',
            '26-29'=>'26-29',
            '30-39'=>'30-39',
            '40-49'=>'40-49',
            '50-59'=>'50-59',
            'Over 60'=>'Over 60');

        $degrees = array(''=>'Please Select',
        'Grammar/Middle School'=>'Grammar/Middle School',
        'High School Diploma'=>'High School Diploma',
        'Some College'=>'Some College',
        'Bachelor\'s Degree'=>'Bachelor\'s Degree',
        'Some Graduate School'=>'Some Graduate School',
        'Graduate Degree'=>'Graduate Degree',
        'PhD'=>'PhD',
        'Other'=>'Other');

        $occupations = array(''=>'Please Select',
        'Accounting/Finance'=>'Accounting/Finance',
        'Executive/Senior Management'=>'Executive/Senior Management',
        'Professional/Managerial'=>'Professional/Managerial',
        'Technical/Engineering'=>'Technical/Engineering',
        'Administrative/Secretarial'=>'Administrative/Secretarial',
        'Sales/Marketing/Advertising'=>'Sales/Marketing/Advertising',
        'Customer Service/Support'=>'Customer Service/Support',
        'College/University Faculty'=>'College/University Faculty',
        'College/University Student'=>'College/University Student',
        'K-12 Student'=>'K-12 Student',
        'Writer/Journalist'=>'Writer/Journalist',
        'Homemaker'=>'Homemaker',
        'Retired'=>'Retired',
        'Currently Not Employed'=>'Currently Not Employed',
        'Other'=>'other');

        $org_types = array(''=>'Please Select',
        'Advertising/Media/Public Relation'=>'Advertising/Media/Public Relation',
        'Agriculture/Forestry'=>'Agriculture/Forestry',
        'Architecture/Engineering/Construction'=>'Architecture/Engineering/Construction',
        'Consulting'=>'Consulting',
        'Entertainment'=>'Entertainment',
        'Finance/Banking/Accounting'=>'Finance/Banking/Accounting',
        'Government'=>'Government',
        'Hospitality/Travel'=>'Hospitality/Travel',
        'Internet-Related Services'=>'Internet-Related Services',
        'Legal Services'=>'Legal Services',
        'Manufacturing/distribution'=>'Manufacturing/Distribution',
        'Marketing/Communications'=>'Marketing/Communications',
        'Medical Services'=>'Medical Services',
        'Nonprofit'=>'Nonprofit',
        'Printing/Graphics'=>'Printing/Graphics',
        'Sales'=>'Sales',
        'Software Development'=>'Software Development',
        'Television/Radio/Print Publishing'=>'Television/Radio/Print Publishing',
        'Transportation/Utilities'=>'Transportation/Utilities',
        'Wholesale/Retail'=>'Wholesale/Retail',
        'Other'=>'Other');
?>
